name: Test CD

on:
  push:
    branches: [ v2_2.0.0 ]

env:
  SERVER_HOST: 91.200.151.163
  SERVER_USERNAME: root
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs: 
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/Bakumov_Medical_Admin/
          git pull
          npm install
          ng build
          sudo rsync -av --delete /root/Bakumov_Medical/Bakumov_Medical_Admin/dist/bakumov-medical-admin/ /var/www/bakumov-medical-admin-v2/
          
